### ISSUE TITLE
new naming scheme for ner models

### ISSUE THREAD

**Issue by jankounchained** [centre-for-humanities-computing/homerCy#20]
to be added in 
a) training workflow
`spacy train config.cfg --output {INPUT NEW NAME}`
b) project.yml -> new set of model names

**Comment by jankounchained** [comment]
according to [spacy naming conventions](https://spacy.io/models#conventions)
our base models should be called `grc_dep_treebanks_(sm|trf)`.

The new models with a trained NER component are then "core", so `grc_core_treebanks_(sm|trf)`
or `grc_homercy_treebanks_(sm|trf)`

**Comment by jankounchained** [comment]
meaining:
sm model we have right now changes to `grc_dep_treebanks_sm`
sm model with NER changes to `grc_homercy_treebanks_sm`

@x-tabdeveloping thoughts?

**Comment by x-tabdeveloping** [comment]
I was thinking we could actually also just try to put the NER-less models into a different directory, and discard them altogether, I don't think there is much of a point in publishing the models that are missing a component, since people can just download the model with the NER and disable it if they don't need it. If we want to keep our training scripts and the `training` folder as the destination for all models, then I think this is a reasonable suggestion, but I would prefer to just make a new folder somewhere else.

**Comment by jankounchained** [comment]
done
